# ---
# pool: ubuntu:latest
# trigger: none
# pr: 
#   -main
# - task: Maven@3
#   displayName: 'Build with Maven'
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'
#     mavenAuthenticateFeed: true


---
pool: ubuntu:latest

trigger: none

pr:
  - main

steps:
  - task: SonarCloudPrepare@3
    inputs:
      SonarCloud: SONAR_CLOUD
      scannerMode: other
      organization: dev.azure.com/vijaysiri048
  - task: Maven@4
    inputs:
      mavenPomFile: pom.xml
      goals: package
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      jdkVersionOption: "1.17" 
      sonarQubeRunAnalysis: true
  - task: CopyFiles@2
    inputs:
      contents: 'target/spring-petclinic*.jar' 
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: $(Build.Repository.Name)

  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: '300'


